name: "storage-starterkit"

services:
  # Postgres DB
  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - ./conf/db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - storage-starterkit-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - storage-starterkit-network

  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    env_file:
      - ./conf/pgadmin.env
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - storage-starterkit-network

networks:
  storage-starterkit-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
